name: Deploy Staging Server
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.STAGING_SSH_USER }}
      SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
      SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
      REMOTE_DOCKER_PORT: 2374
      DOCKER_HOST: localhost:2374
    steps:
      - uses: actions/checkout@master
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      - name: Tunnel SSH
        run: ssh -fNL $DOCKER_HOST:staging:$REMOTE_DOCKER_PORT staging
      - name: Print Docker Version
        run: docker --version
